### ISSUE TITLE
Move to an org?

### ISSUE THREAD

**Issue by carols10cents** [compatriot/compatriot#21]
Hey @TheJefe, wdyt about moving this to an org before codemash, since I'm not really doing much on it anymore? :)

**Comment by TheJefe** [comment]
Sure! Sounds like a great idea! If you don't jump on it, I'll be happy to handle it later tonight

**Comment by TheJefe** [comment]
Looks like the username compatriot is already taken, but unused. I've sent a request to github to have it released.  Hopefully they do, otherwise one will need to be made up.

**Comment by TheJefe** [comment]
Got the name!!!! You'll have to do the transfer, as I do not have the rights for it.  You'll first have to accept the invitation to the organization in order to do it.

**Comment by carols10cents** [comment]
Done!!!!!! Now the org needs a logo :)
